POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Javier Gdovic",
  "username": "j.GEeeee",
  "email": "fakeEmail@billy.biz",
  "address": {
    "street": "Roblox Trail",
    "suite": "Suite 429",
    "city": "Pitt",
    "zipcode": "58804-1099",
    "geo": {
      "lat": "24.8918",
      "lng": "21.8984"
    }
  },
  "phone": "210.067.6132",
  "website": "elvis.io",
  "company": {
    "name": "Johns Group",
    "catchPhrase": "Configurable multimedia task-force",
    "bs": "generate enterprise e-tailers"
  }
}